#!/usr/bin/env node
// Generates every brand asset from scripts/brand/geometry.mjs.
//
//   node scripts/brand/build-icons.mjs
//
// Writes into apps/web, apps/mobile/androidApp and apps/mobile/iosApp. All
// outputs are committed — this script exists so the geometry has one home, not
// so assets are built on demand. Re-run it after editing geometry.mjs.
//
// sharp is resolved out of apps/web/node_modules (it is a web dependency, used
// there for KB PDF rendering); there is no separate install for this script.

import { createRequire } from 'node:module';
import { mkdir, writeFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  COLORS, PRIMARY, MONO, FAVICON,
  bounds, boundingRadius, chevronOutline, platePositions,
  markSvg, tileSvg, markPaths, redPath, navyPath,
} from './geometry.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const WEB = join(ROOT, 'apps/web');
const ANDROID = join(ROOT, 'apps/mobile/androidApp/src/main/res');
const IOS = join(ROOT, 'apps/mobile/iosApp/iosApp');

const require = createRequire(join(WEB, 'package.json'));
const sharp = require('sharp');

const written = [];

async function put(path, contents) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
  written.push(path.slice(ROOT.length + 1));
}

// `opaque` strips the alpha channel: App Store Connect rejects an AppIcon with
// transparency, and iOS composites a transparent apple-touch-icon onto black.
async function png(path, svg, size, { opaque = false } = {}) {
  let pipe = sharp(Buffer.from(svg), { density: 384 })
    .resize(size, size, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } });
  if (opaque) pipe = pipe.flatten({ background: COLORS.ground });
  const buf = await pipe.png({ compressionLevel: 9 }).toBuffer();
  await put(path, buf);
}

async function webp(path, svg, size) {
  const buf = await sharp(Buffer.from(svg), { density: 384 })
    .resize(size, size)
    .webp({ quality: 95 })
    .toBuffer();
  await put(path, buf);
}

const GENERATED = 'Generated by scripts/brand/build-icons.mjs from scripts/brand/geometry.mjs. Do not edit by hand.';

/* ── web ──────────────────────────────────────────────────────────────── */

async function buildWeb() {
  await put(join(WEB, 'public/brand/logo.svg'), markSvg(PRIMARY));
  await put(join(WEB, 'public/brand/logo-mono.svg'), markSvg(MONO, { fill: 'currentColor' }));
  // Reversed: Penn red has no contrast on navy, so the upper chevron lifts to
  // the muted blue and the lower goes white.
  await put(join(WEB, 'public/brand/logo-reversed.svg'),
    markSvg(PRIMARY, { upper: COLORS.ghost, lower: COLORS.white }));
  await put(join(WEB, 'public/brand/icon.svg'), tileSvg(PRIMARY, { inset: 0.94 }));

  // The favicon cut: no plates, thicker bands, wider gap.
  await put(join(WEB, 'app/icon.svg'), tileSvg(FAVICON, { inset: 0.94 }));

  await png(join(WEB, 'app/apple-icon.png'), tileSvg(PRIMARY, { inset: 0.94 }), 180, { opaque: true });
  await png(join(WEB, 'public/brand/icon-192.png'), tileSvg(PRIMARY, { inset: 0.94 }), 192);
  await png(join(WEB, 'public/brand/icon-512.png'), tileSvg(PRIMARY, { inset: 0.94 }), 512);
  // Maskable: Android PWA crops to a circle of 80% diameter, so pull the mark in.
  await png(join(WEB, 'public/brand/icon-maskable-512.png'), tileSvg(PRIMARY, { inset: 0.88 }), 512);
  await png(join(WEB, 'public/brand/og.png'), tileSvg(PRIMARY, { inset: 0.94 }), 512, { opaque: true });

  // Path data for the inline React mark, so the header cannot drift from the
  // icon files. Consumed by apps/web/components/ui/Logo.tsx.
  const b = bounds(PRIMARY);
  const pad = 2;
  const viewBox = [b.minX - pad, b.minY - pad, b.width + pad * 2, b.height + pad * 2]
    .map((v) => Number(v.toFixed(4)))
    .join(' ');
  await put(join(WEB, 'lib/brandPaths.ts'), `// ${GENERATED}
// The chevronel. See docs/design/logo.md for the construction.

export const BRAND_COLORS = {
  navy: '${COLORS.navy}',
  red: '${COLORS.red}',
  ground: '${COLORS.ground}',
  ghost: '${COLORS.ghost}',
} as const;

export const BRAND_VIEW_BOX = '${viewBox}';

/** Upper (Penn red) chevron. */
export const BRAND_UPPER_PATH = '${redPath(PRIMARY)}';

/** Upper chevron, monochrome cut: thinner, so weight alone separates the two. */
export const BRAND_UPPER_PATH_MONO = '${redPath(MONO)}';

/** Lower (Penn navy) chevron, with the three plates as evenodd holes. */
export const BRAND_LOWER_PATH = '${navyPath(PRIMARY)}';
`);

  // Stock create-next-app scaffolding the mark replaces.
  for (const stale of [
    'app/favicon.ico', 'public/file.svg', 'public/globe.svg',
    'public/next.svg', 'public/vercel.svg', 'public/window.svg',
  ]) {
    await rm(join(WEB, stale), { force: true });
  }
}

/* ── android ──────────────────────────────────────────────────────────── */

// Adaptive icons are drawn on a 108dp canvas; only the central 72dp is safe and
// circular launcher masks show a 66dp circle. Scale so the mark's bounding
// radius (43.08 artboard units) lands inside that circle with margin.
const ADAPTIVE_SCALE = Number((33 / boundingRadius(PRIMARY) * 0.965).toFixed(4));

function vectorDrawable(inner, { viewport = 100, size = 108 } = {}) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="${viewport}"
    android:viewportHeight="${viewport}">
${inner}
</vector>
`;
}

function adaptiveGroup(cut, { upper, lower }) {
  const b = bounds(cut);
  const s = ADAPTIVE_SCALE;
  const tx = (54 - b.cx * s).toFixed(4);
  const ty = (54 - b.cy * s).toFixed(4);
  return `    <group
        android:scaleX="${s}"
        android:scaleY="${s}"
        android:translateX="${tx}"
        android:translateY="${ty}">
        <path android:fillColor="${upper}" android:pathData="${redPath(cut)}"/>
        <path android:fillColor="${lower}" android:fillType="evenOdd" android:pathData="${navyPath(cut)}"/>
    </group>`;
}

async function buildAndroid() {
  await put(join(ANDROID, 'drawable/ic_launcher_background.xml'), vectorDrawable(
    `    <path android:fillColor="${COLORS.ground}" android:pathData="M0,0h108v108h-108z"/>`,
    { viewport: 108 }));

  await put(join(ANDROID, 'drawable/ic_launcher_foreground.xml'), vectorDrawable(
    adaptiveGroup(PRIMARY, { upper: COLORS.red, lower: COLORS.navy }), { viewport: 108 }));

  // Themed icons tint a single layer, so the plates must be real holes here too.
  await put(join(ANDROID, 'drawable/ic_launcher_monochrome.xml'), vectorDrawable(
    adaptiveGroup(MONO, { upper: '#FF000000', lower: '#FF000000' }), { viewport: 108 }));

  // In-app mark. Ground included so it is theme-independent; Compose clips it.
  await put(join(ANDROID, 'drawable/ic_brand_mark.xml'), vectorDrawable(
    `    <path android:fillColor="${COLORS.ground}" android:pathData="M0,0h100v100h-100z"/>\n` +
    `    <path android:fillColor="${COLORS.red}" android:pathData="${redPath(PRIMARY)}"/>\n` +
    `    <path android:fillColor="${COLORS.navy}" android:fillType="evenOdd" android:pathData="${navyPath(PRIMARY)}"/>`,
    { viewport: 100, size: 100 }));

  const adaptive = (round) => `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`;
  await put(join(ANDROID, 'mipmap-anydpi-v26/ic_launcher.xml'), adaptive(false));
  await put(join(ANDROID, 'mipmap-anydpi-v26/ic_launcher_round.xml'), adaptive(true));

  // minSdk is 24, so API 24-25 still needs raster mipmaps with their own ground.
  const square = tileSvg(PRIMARY, { shape: 'rounded', inset: 0.86 });
  const round = tileSvg(PRIMARY, { shape: 'circle', inset: 0.78 });
  for (const [bucket, size] of [['mdpi', 48], ['hdpi', 72], ['xhdpi', 96], ['xxhdpi', 144], ['xxxhdpi', 192]]) {
    await webp(join(ANDROID, `mipmap-${bucket}/ic_launcher.webp`), square, size);
    await webp(join(ANDROID, `mipmap-${bucket}/ic_launcher_round.webp`), round, size);
  }

  // The widget picker previews @mipmap/ic_launcher, which is now branded.
}

/* ── ios ──────────────────────────────────────────────────────────────── */

async function buildIos() {
  const cat = join(IOS, 'Assets.xcassets');
  const info = { info: { author: 'xcode', version: 1 } };

  await put(join(cat, 'Contents.json'), JSON.stringify(info, null, 2) + '\n');

  await put(join(cat, 'AppIcon.appiconset/Contents.json'), JSON.stringify({
    images: [{ filename: 'AppIcon-1024.png', idiom: 'universal', platform: 'ios', size: '1024x1024' }],
    ...info,
  }, null, 2) + '\n');
  await png(join(cat, 'AppIcon.appiconset/AppIcon-1024.png'), tileSvg(PRIMARY, { inset: 0.94 }), 1024, { opaque: true });

  // Accent stays Shift Blue — the mark's palette is deliberately not the UI accent.
  await put(join(cat, 'AccentColor.colorset/Contents.json'), JSON.stringify({
    colors: [{
      color: {
        'color-space': 'srgb',
        components: { alpha: '1.000', blue: '0xFC', green: '0x61', red: '0x00' },
      },
      idiom: 'universal',
    }],
    ...info,
  }, null, 2) + '\n');

  // Swift geometry mirror, so the in-app mark cannot drift from the icon.
  const b = bounds(PRIMARY);
  const pt = (p) => `CGPoint(x: ${p[0].toFixed(4)}, y: ${p[1].toFixed(4)})`;
  const list = (pts) => pts.map(pt).join(',\n        ');
  await put(join(IOS, 'BrandMarkGeometry.swift'), `// ${GENERATED}
// The chevronel, on the shared 100x100 artboard. See docs/design/logo.md.

import CoreGraphics

enum BrandMarkGeometry {
    static let artboard: CGFloat = 100

    /// Upper (Penn red) chevron outline.
    static let upper: [CGPoint] = [
        ${list(chevronOutline(PRIMARY.red))},
    ]

    /// Lower (Penn navy) chevron outline.
    static let lower: [CGPoint] = [
        ${list(chevronOutline(PRIMARY.navy))},
    ]

    /// Plate centres, on the lower chevron's centreline.
    static let plates: [CGPoint] = [
        ${list(platePositions(PRIMARY.navy, PRIMARY.plateSpacing))},
    ]

    static let plateRadius: CGFloat = ${PRIMARY.plateRadius}

    /// Tight bounds of the whole mark, for centring inside a tile.
    static let markBounds = CGRect(
        x: ${b.minX.toFixed(4)}, y: ${b.minY.toFixed(4)},
        width: ${b.width.toFixed(4)}, height: ${b.height.toFixed(4)})
}
`);
}

/* ── run ──────────────────────────────────────────────────────────────── */

await buildWeb();
await buildAndroid();
await buildIos();

console.log(`adaptive icon scale ${ADAPTIVE_SCALE} (bounding radius ${boundingRadius(PRIMARY).toFixed(2)} -> ${(boundingRadius(PRIMARY) * ADAPTIVE_SCALE).toFixed(2)} of the 33dp safe circle)`);
console.log(`${written.length} files written:`);
for (const f of written) console.log('  ' + f);
