// Generated by scripts/brand/build-icons.mjs from scripts/brand/geometry.mjs. Do not edit by hand.
// The chevronel. See docs/design/logo.md for the construction.

export const BRAND_COLORS = {
  navy: '#011F5B',
  red: '#990000',
  ground: '#F4F3F0',
  ghost: '#5B72A8',
} as const;

export const BRAND_VIEW_BOX = '12.8932 13.6894 74.2135 73.0982';

/** Upper (Penn red) chevron. */
export const BRAND_UPPER_PATH =
  'M16.3523 51.5803L50 15.6894L83.6477 51.5803L76.3523 58.4197L50 30.3106L23.6477 58.4197Z';

/** Upper chevron, monochrome cut: thinner, so weight alone separates the two. */
export const BRAND_UPPER_PATH_MONO =
  'M17.4466 52.6062L50 17.8826L82.5534 52.6062L77.4466 57.3938L50 28.1174L22.5534 57.3938Z';

/** Lower (Penn navy) chevron, with the three plates as evenodd holes. */
export const BRAND_LOWER_PATH =
  'M14.8932 75.2124L50 37.7652L85.1068 75.2124L74.8932 84.7876L50 58.2348L25.1068 84.7876ZM44.8 48a5.2 5.2 0 1 0 10.4 0a5.2 5.2 0 1 0 -10.4 0ZM31.1212 62.5907a5.2 5.2 0 1 0 10.4 0a5.2 5.2 0 1 0 -10.4 0ZM58.4788 62.5907a5.2 5.2 0 1 0 10.4 0a5.2 5.2 0 1 0 -10.4 0Z';
