#!/usr/bin/env bash
# QA mode: point every tool at the LOCAL Supabase stack, and make that enforceable.
#
# THE MARKER IS THE SINGLE SOURCE OF TRUTH.
#
# `.qa-mode` at the repo root is the only fact. Nothing copies or swaps a .env file,
# because both apps/web/.env.local and .env.localdev.local are gitignored, so a swap
# that half-fails destroys a config git cannot restore. Instead the environment is
# DERIVED from the marker at process start:
#
#   marker present -> local stack (127.0.0.1)
#   marker absent  -> remote staging project (your normal default, untouched)
#
# Because there is one fact rather than a flag plus a copied file, the two can never
# disagree, which is the "QA data leaking into the app and vice versa" failure this
# exists to prevent.
#
# LIFECYCLE IS ENFORCED BY THE HARNESS, NOT BY AN AGENT REMEMBERING.
#
#   scripts/hooks/qa-mode-lifecycle.js on SessionEnd   -> clears the marker
#   scripts/hooks/qa-mode-lifecycle.js on SessionStart -> deletes any marker left over
#                                                         from a previous session and
#                                                         says so in-context
#
# The SessionStart half is the real backstop: a crash or `kill -9` skips SessionEnd,
# but the next session still begins clean. That is why no time-based expiry is needed.
#
#   scripts/hooks/qa-remote-guard.js on PreToolUse(Bash) -> while the marker exists,
#   DENIES any command that names the remote project ref or a *.supabase.co host.
#
# Usage:
#   qa-mode.sh on       enable (starts the local stack if needed)
#   qa-mode.sh off      disable
#   qa-mode.sh status   print LOCAL or REMOTE; exit 0 if QA mode is on, 1 if off
#   qa-mode.sh require  hard gate: exit non-zero unless QA mode is on AND local is reachable
#   qa-mode.sh env      print `export` lines for the local environment (for eval)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MARKER="$REPO_ROOT/.qa-mode"
LOCAL_DB="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
LOCAL_API="http://127.0.0.1:54321"

red()  { printf '\033[31m%s\033[0m\n' "$*"; }
grn()  { printf '\033[32m%s\033[0m\n' "$*"; }
ylw()  { printf '\033[33m%s\033[0m\n' "$*"; }

local_up() { curl -sf -o /dev/null --max-time 3 "$LOCAL_API/rest/v1/" -H "apikey: x" 2>/dev/null || pg_isready -h 127.0.0.1 -p 54322 -q 2>/dev/null; }

remote_ref() { cat "$REPO_ROOT/supabase/.temp/project-ref" 2>/dev/null || echo ""; }

cmd_on() {
  if ! local_up; then
    ylw "Local stack is not up. Starting it..."
    (cd "$REPO_ROOT" && supabase start)
  fi
  cat > "$MARKER" <<EOF
# QA mode. Generated by scripts/qa/qa-mode.sh. Gitignored.
# While this file exists, every tool targets the LOCAL Supabase stack and
# scripts/hooks/qa-remote-guard.js denies any command naming the remote project.
enabled_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
pid=$$
EOF
  grn "QA mode ON. Target: $LOCAL_API (local)."
  echo "  Remote project '$(remote_ref)' is now BLOCKED for Bash commands."
  echo "  Cleared automatically at session end, or with: scripts/qa/qa-mode.sh off"
}

cmd_off() {
  rm -f "$MARKER"
  grn "QA mode OFF. Target: remote staging project (normal default)."
}

cmd_status() {
  if [ -f "$MARKER" ]; then
    grn "LOCAL  (QA mode ON)"
    sed -n 's/^enabled_at=/  enabled at /p' "$MARKER"
    local_up || red "  WARNING: marker present but the local stack is NOT reachable."
    return 0
  fi
  echo "REMOTE  (QA mode off, normal default)"
  return 1
}

# The gate the ship-check persona and skill call before touching any database.
cmd_require() {
  if [ ! -f "$MARKER" ]; then
    red "REFUSING: QA mode is OFF, so database commands would hit the REMOTE staging project."
    echo "Enable it first:  scripts/qa/qa-mode.sh on" >&2
    exit 2
  fi
  if ! local_up; then
    red "REFUSING: QA mode is on but the local stack is not reachable at $LOCAL_API."
    echo "Start it:  supabase start" >&2
    exit 3
  fi
  grn "OK: QA mode on, local stack reachable at $LOCAL_API."
}

cmd_env() {
  local envfile="$REPO_ROOT/apps/web/.env.localdev.local"
  if [ ! -f "$MARKER" ]; then
    red "QA mode is off. Refusing to emit local env." >&2
    exit 2
  fi
  [ -f "$envfile" ] || { red "Missing $envfile" >&2; exit 4; }
  # Emit as exports so real process env wins over Next.js's .env.local.
  grep -E '^[A-Z][A-Z0-9_]*=' "$envfile" | sed 's/^/export /'
  echo "export SUPABASE_ENV=LOCAL"
}

case "${1:-status}" in
  on)      cmd_on ;;
  off)     cmd_off ;;
  status)  cmd_status ;;
  require) cmd_require ;;
  env)     cmd_env ;;
  *) echo "usage: qa-mode.sh {on|off|status|require|env}" >&2; exit 64 ;;
esac
