#!/usr/bin/env bash
# Generate the staging/production seed set from the local database.
#
#   ./scripts/gen-prod-seed.sh                     # staging: carries passwords
#   PROD_SEED_NO_PASSWORDS=1 ./scripts/gen-prod-seed.sh   # production: reset-only accounts
#
# Writes supabase/seeds/prod/01..06. Mirrors scripts/gen-harnwell-seed.sql: every tier is
# literal SQL so the payload is reviewable in a diff, byte-identical between staging and
# prod, and repeatable. Deliberately not pg_dump.
#
# ---------------------------------------------------------------------------
# TWO DESIGN FACTS THAT DRIVE EVERYTHING HERE
#
# 1. MIGRATE AUTHORED INPUTS, REGENERATE DERIVED OUTPUTS.
#    operating_profiles, staffing_patterns, operating_calendar, float_routing and every
#    shift_blocks row are DERIVED: apply_compiled_season produces them from the authoring
#    tables. This script never emits them. The runbook runs the RPC online instead.
#
# 2. BLOCK IDS ARE REGENERATED, SO EVERY BLOCK-SCOPED ROW RELINKS BY NATURAL KEY.
#    shift_block_assignments, preferences AND draft_block_assignments all reference
#    block_id. Those uuids are random per generation, so exporting them verbatim would
#    orphan every row. Each is emitted as INSERT ... SELECT joined to shift_blocks on
#    (house_id, block_start_at), the same natural key the Harnwell seed already uses.
#    This is why tiers 04 to 06 must load AFTER the season apply.
#
# ---------------------------------------------------------------------------
# NORMALIZATION. The local Harnwell schedule carries artifacts from orchestrator testing
# (a real float against Aaron's 2026-07-25 shift). Every tier that reads the schedule runs
# inside a transaction that undoes them and is then ROLLED BACK, so this script never
# modifies the local database. Verified against clean same-weekday blocks: 2026-07-18 and
# 2026-08-01 each hold exactly 2 seats, both 'scheduled'.
set -euo pipefail

DB="${PROD_SEED_DB_URL:-postgresql://postgres:postgres@127.0.0.1:54322/postgres}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/seeds/prod"
mkdir -p "$OUT"

# Accounts that migrate. Everything else is fixture data (Alice Du Bois and friends).
#   fbb00000% / a012a6b8  -> 11 real Harnwell people (10 workers + HM Mitchelle Majeski)
#   9ce70000%             -> 9 real Gregory people (8 sw + SM Eleni)
#   5ca50000%...41 / ...42 -> Hana (hm) + Diana (rsm): Gregory PLACEHOLDERS, not real
#                             people, carried by explicit decision so Gregory has a
#                             coverage-notification recipient
#   a0000000%...0b        -> project administrator (admin@upenn.edu)
#   a111ed00%...01        -> Allied pseudo-account (allied-house)
PEOPLE="(u.user_id::text LIKE 'fbb00000%'
  OR u.user_id::text LIKE '9ce70000%'
  OR u.user_id IN ('a012a6b8-4f8d-4837-976c-7b0fbc60f8f9',
                   '5ca50000-0000-4000-8000-000000000041',
                   '5ca50000-0000-4000-8000-000000000042',
                   'a0000000-0000-4000-8000-00000000000b',
                   'a111ed00-0000-4000-8000-000000000001'))"

# Harnwell's schedule is cut at the Summer 2026 season end. The 456 blocks from Aug 21 to
# Sep 7 (200 staffed) are knowingly NOT migrated: no season covers them, so the compiler
# would not own them.
CUTOFF="'2026-08-21 00:00:00-04'::timestamptz"

NORMALIZE="
  UPDATE shift_block_assignments SET status='scheduled', parent_float_id=NULL
   WHERE parent_float_id IS NOT NULL AND status='pending_float_out';
  DELETE FROM shift_block_assignments
   WHERE parent_float_id IS NOT NULL AND status='vacant';
  UPDATE shift_blocks SET coverage_locked_at=NULL WHERE coverage_locked_at IS NOT NULL;
"

PW_EXPR="a.encrypted_password"
PW_NOTE="-- Passwords carried verbatim (STAGING build)."
if [ -n "${PROD_SEED_NO_PASSWORDS:-}" ]; then
  PW_EXPR="NULL"
  PW_NOTE="-- Passwords deliberately NULL (PRODUCTION build): every account must go through
-- GoTrue recovery onboarding. Requires SMTP to be configured first."
fi

emit() { local f="$OUT/$1"; shift
  psql "$DB" -tAX -v ON_ERROR_STOP=1 -o "$f" -c "$1"
  printf '%s\n' "$(cat "$f")" > "$f"
  printf '  %-24s %6s lines  %5s\n' "$(basename "$f")" "$(wc -l < "$f" | tr -d ' ')" "$(du -h "$f" | cut -f1)"
}

echo "Generating seed set into supabase/seeds/prod/"

emit 01-reference.sql "
SELECT E'-- Tier 1: houses, system config, duty routing\n-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.\n-- Idempotent.\nBEGIN;\n'
UNION ALL SELECT E'-- launch_state stays pre_launch for ALL houses. The cutover flips a house live\n-- EXPLICITLY, and only once that house has a published schedule (see the runbook).'
UNION ALL SELECT 'INSERT INTO houses (id, name, desk_phone, is_staffable, launch_state) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,''pre_launch'')', id, name, desk_phone, is_staffable), E',\n' ORDER BY id)
     || E'\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, desk_phone=EXCLUDED.desk_phone, is_staffable=EXCLUDED.is_staffable;' FROM houses
UNION ALL SELECT E'\n-- system_config. The simulated clock is gated by ROLE now, not by a system_config key\n-- (migration 20260805000001) -- no allow_time_travel row is needed in any environment.'
UNION ALL SELECT 'INSERT INTO system_config (config_key, config_value, value_type, notes) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L::value_type_enum,%L)', config_key, config_value, value_type, notes), E',\n' ORDER BY config_key)
     || E'\nON CONFLICT (config_key) DO UPDATE SET config_value=EXCLUDED.config_value;'
     FROM system_config WHERE config_key <> 'allow_time_travel'
UNION ALL SELECT E'\n-- duty routing (issue type -> tier, with day/time/season windows)'
UNION ALL SELECT COALESCE((SELECT 'INSERT INTO routing_rules (rule_id, issue_type, tier, day_type, window_start, window_end, season_scope, priority, active, notes) VALUES' || E'\n'
     || string_agg(format('  (%L,%L,%L,%L,%L,%L,%L,%s,%L,%L)', rule_id::text, issue_type, tier, day_type, window_start, window_end, season_scope, priority, active, notes), E',\n' ORDER BY priority)
     || E'\nON CONFLICT (rule_id) DO NOTHING;' FROM routing_rules), '-- (none)')
UNION ALL SELECT E'\nCOMMIT;'"

emit 02-people.sql "
SELECT E'-- Tier 2: accounts, roles, memberships\n-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.\n--\n$PW_NOTE\n--\n-- FLAGGED, NOT HIDDEN: Hana Gregory (hm) and Diana Gregory (rsm) are NOT real people.\n-- They are carried so Gregory has a coverage recipient. The 9 Gregory accounts use\n-- firstname@upenn.edu placeholder addresses that MUST be replaced with deliverable Penn\n-- addresses before the production load.\nBEGIN;\n'
UNION ALL SELECT 'INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password,'
UNION ALL SELECT '  email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data,'
UNION ALL SELECT '  confirmation_token, recovery_token, email_change_token_new, email_change) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,''authenticated'',''authenticated'',%L,%s, now(),now(),now(), %L::jsonb, %L::jsonb, '''','''','''','''')',
       '00000000-0000-0000-0000-000000000000', a.id::text, a.email,
       CASE WHEN $PW_EXPR IS NULL THEN 'NULL' ELSE quote_literal($PW_EXPR) END,
       a.raw_app_meta_data::text, a.raw_user_meta_data::text), E',\n' ORDER BY a.email)
     || E'\nON CONFLICT (id) DO NOTHING;'
     FROM auth.users a JOIN users u ON u.user_id=a.id WHERE $PEOPLE
UNION ALL SELECT E'\nINSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L::jsonb,''email'', now(),now(),now())', u.user_id::text, u.user_id::text,
       json_build_object('sub', u.user_id::text, 'email', u.email)::text), E',\n' ORDER BY u.email)
     || E'\nON CONFLICT (provider, provider_id) DO NOTHING;' FROM users u WHERE $PEOPLE
UNION ALL SELECT E'\nINSERT INTO users (user_id, name, email, home_house_id, is_active, broadcast_subscribed) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,%L,%L)', u.user_id::text, u.name, u.email, u.home_house_id, u.is_active, u.broadcast_subscribed), E',\n' ORDER BY u.email)
     || E'\nON CONFLICT (user_id) DO UPDATE SET name=EXCLUDED.name, email=EXCLUDED.email, home_house_id=EXCLUDED.home_house_id, is_active=EXCLUDED.is_active;'
     FROM users u WHERE $PEOPLE
UNION ALL SELECT E'\nINSERT INTO user_roles (user_id, role, scope_house_id) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L::user_role_enum,%L)', r.user_id::text, r.role, r.scope_house_id), E',\n' ORDER BY r.user_id::text, r.role::text)
     || E'\nON CONFLICT DO NOTHING;' FROM user_roles r JOIN users u USING (user_id) WHERE $PEOPLE
UNION ALL SELECT E'\n-- season-scoped membership; users.home_house_id is the cache of the row covering today'
UNION ALL SELECT COALESCE((SELECT 'INSERT INTO user_house_memberships (membership_id, user_id, house_id, effective_from, effective_to, applied_at, note) VALUES' || E'\n'
     || string_agg(format('  (%L,%L,%L,%L,%L,%L,%L)', m.membership_id::text, m.user_id::text, m.house_id, m.effective_from, m.effective_to, m.applied_at, m.note), E',\n' ORDER BY m.user_id::text)
     || E'\nON CONFLICT (membership_id) DO NOTHING;' FROM user_house_memberships m JOIN users u USING (user_id) WHERE $PEOPLE), '-- (none)')
UNION ALL SELECT E'\n-- the urgent-notification terminal contact must resolve to an active user'
UNION ALL SELECT 'UPDATE system_config SET config_value=''a0000000-0000-4000-8000-00000000000b'' WHERE config_key=''project_administrator_user_id'';'
UNION ALL SELECT E'\nCOMMIT;'"

emit 03-season.sql "
SELECT E'-- Tier 3: AUTHORED season configuration only\n-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.\n--\n-- Writes authoring tables ONLY. operating_profiles, staffing_patterns,\n-- operating_calendar, float_routing and shift_blocks are DERIVED and are produced by\n-- apply_compiled_season, which the runbook runs (dry-run first) after this loads.\nBEGIN;\n'
UNION ALL SELECT 'INSERT INTO operating_seasons (season_id, season_name, slug, start_date, end_date, scheduling_mode, hours_cap, cap_enforcement, shift_start_bound, shift_end_bound, created_by, created_at, preference_deadline) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,%L,%L::scheduling_mode_enum,%s,%L::cap_enforcement_enum,%L,%L,''a0000000-0000-4000-8000-00000000000b'', now(),%L)',
       season_id::text, season_name, slug, start_date, end_date, scheduling_mode, hours_cap, cap_enforcement, shift_start_bound, shift_end_bound, preference_deadline), E',\n' ORDER BY start_date)
     || E'\nON CONFLICT (season_id) DO NOTHING;' FROM operating_seasons
UNION ALL SELECT E'\n-- per-house day-type bands; an empty band list means closed that day type'
UNION ALL SELECT 'INSERT INTO season_house_windows (window_id, season_id, house_id, start_date, end_date, weekday_bands, weekend_bands) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,%L,%L::jsonb,%L::jsonb)', window_id::text, season_id::text, house_id, start_date, end_date, weekday_bands::text, weekend_bands::text), E',\n' ORDER BY house_id)
     || E'\nON CONFLICT (window_id) DO NOTHING;' FROM season_house_windows
UNION ALL SELECT E'\n' || COALESCE((SELECT 'INSERT INTO season_float_windows (window_id, season_id, start_date, end_date) VALUES' || E'\n'
     || string_agg(format('  (%L,%L,%L,%L)', window_id::text, season_id::text, start_date, end_date), E',\n')
     || E'\nON CONFLICT (window_id) DO NOTHING;' FROM season_float_windows), '-- (no float windows)')
UNION ALL SELECT E'\n-- the scheduling period the builder and preferences hang off'
UNION ALL SELECT 'INSERT INTO scheduling_periods (period_id, period_name, profile_name, start_date, end_date, preference_deadline) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,%L,%L)', period_id::text, period_name, profile_name, start_date, end_date, preference_deadline), E',\n')
     || E'\nON CONFLICT (period_id) DO NOTHING;' FROM scheduling_periods WHERE period_id='5ea50000-0000-4000-8000-000000000001'
UNION ALL SELECT E'\nCOMMIT;'"

# Tiers 04-06 are block-scoped and relink by (house_id, block_start_at).
emit 04-harnwell-schedule.sql "
BEGIN;
$NORMALIZE
SELECT E'-- Tier 4: the Harnwell schedule, relinked by natural key\n-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.\n--\n-- Load AFTER apply_compiled_season: block ids are regenerated, so every row is matched\n-- to whatever block now owns that (house_id, block_start_at) slot.\n--\n-- Orchestrator-test artifacts were normalized out during generation (a float against\n-- Aaron 2026-07-25 flipped 8 seats to pending_float_out, injected 8 surplus vacant seats,\n-- and left a one-way coverage lock on 4 blocks).\n--\n-- Cut at the Summer 2026 season end. The Aug 21 - Sep 7 tail is knowingly not migrated.\nBEGIN;\n'
UNION ALL SELECT 'INSERT INTO shift_block_assignments (block_id, user_id, status, vacancy_origin)'
UNION ALL SELECT 'SELECT b.block_id, v.user_id::uuid, v.status::shift_status_enum, v.vacancy_origin::vacancy_origin_enum'
UNION ALL SELECT 'FROM (VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L)', sb.block_start_at, sba.user_id::text, sba.status, sba.vacancy_origin),
       E',\n' ORDER BY sb.block_start_at, sba.user_id::text NULLS LAST)
     FROM shift_block_assignments sba JOIN shift_blocks sb USING (block_id)
     WHERE sb.house_id='harnwell' AND sb.block_start_at < $CUTOFF
UNION ALL SELECT E') AS v(block_start_at, user_id, status, vacancy_origin)'
UNION ALL SELECT 'JOIN shift_blocks b ON b.house_id=''harnwell'' AND b.block_start_at = v.block_start_at::timestamptz'
UNION ALL SELECT E'WHERE NOT EXISTS (SELECT 1 FROM shift_block_assignments x WHERE x.block_id=b.block_id AND x.user_id IS NOT DISTINCT FROM v.user_id::uuid);'
UNION ALL SELECT E'\nCOMMIT;';
ROLLBACK;"

emit 05-preferences.sql "
SELECT E'-- Tier 5: submitted preferences and per-worker hour targets\n-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.\n--\n-- Real Summer 2026 submissions from the 9 Harnwell and 9 Gregory workers. Gregory has no\n-- assignments by design: these preferences are the AI builder input for its first\n-- Gregory schedule.\n--\n-- Load AFTER apply_compiled_season: preferences reference block_id, which is regenerated.\nBEGIN;\n'
UNION ALL SELECT 'INSERT INTO preferences (user_id, block_id, period_id, status)'
UNION ALL SELECT 'SELECT v.user_id::uuid, b.block_id, v.period_id::uuid, v.status::preference_status_enum'
UNION ALL SELECT 'FROM (VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,%L)', p.user_id::text, sb.house_id, sb.block_start_at, p.period_id::text, p.status),
       E',\n' ORDER BY p.user_id::text, sb.block_start_at)
     FROM preferences p JOIN users u USING (user_id) JOIN shift_blocks sb ON sb.block_id=p.block_id WHERE $PEOPLE
UNION ALL SELECT E') AS v(user_id, house_id, block_start_at, period_id, status)'
UNION ALL SELECT 'JOIN shift_blocks b ON b.house_id=v.house_id AND b.block_start_at = v.block_start_at::timestamptz'
UNION ALL SELECT E'ON CONFLICT DO NOTHING;'
UNION ALL SELECT E'\n' || COALESCE((SELECT 'INSERT INTO period_targets (period_id, user_id, target_hours, opted_out) VALUES' || E'\n'
     || string_agg(format('  (%L,%L,%s,%L)', t.period_id::text, t.user_id::text, t.target_hours, t.opted_out), E',\n' ORDER BY t.user_id::text)
     || E'\nON CONFLICT DO NOTHING;' FROM period_targets t JOIN users u USING (user_id) WHERE $PEOPLE), '-- (no targets)')
UNION ALL SELECT E'\nCOMMIT;'"

emit 06-kb.sql "
SELECT E'-- Tier 6: Desk Assistant knowledge base, with embeddings carried verbatim\n-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.\n--\n-- Vectors are copied rather than re-embedded: identical retrieval behaviour and no\n-- Voyage spend. Chat transcripts (da_conversations / da_messages) are deliberately NOT\n-- migrated; production starts with an empty conversation history.\nBEGIN;\n'
UNION ALL SELECT 'INSERT INTO kb_documents (document_id, title, source_type, source_ref, house_scope, sensitivity, allowed_roles, created_at) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%L,%L,%L::text[],%L::da_sensitivity_enum,%L::text[], now())', document_id::text, title, source_type, source_ref, house_scope::text, sensitivity, allowed_roles::text), E',\n' ORDER BY title)
     || E'\nON CONFLICT (document_id) DO NOTHING;' FROM kb_documents
UNION ALL SELECT E'\nINSERT INTO kb_chunks (chunk_id, document_id, chunk_index, content, embedding, house_scope, sensitivity, allowed_roles, token_count, temporality, effective_from, effective_until) VALUES'
UNION ALL SELECT string_agg(format('  (%L,%L,%s,%L,%L::vector,%L::text[],%L::da_sensitivity_enum,%L::text[],%s,%L,%L,%L)',
       chunk_id::text, document_id::text, chunk_index, content, embedding::text, house_scope::text, sensitivity, allowed_roles::text, token_count, temporality, effective_from, effective_until),
       E',\n' ORDER BY document_id::text, chunk_index)
     || E'\nON CONFLICT (chunk_id) DO NOTHING;' FROM kb_chunks
UNION ALL SELECT E'\nCOMMIT;'"

echo
echo "Done. Load order: 01, 02, 03, [apply_compiled_season], 04, 05, 06."
