-- Tier 1: houses, system config, duty routing
-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.
-- Idempotent.
BEGIN;

-- launch_state stays pre_launch for ALL houses. The cutover flips a house live
-- EXPLICITLY, and only once that house has a published schedule (see the runbook).
INSERT INTO houses (id, name, desk_phone, is_staffable, launch_state) VALUES
  ('allied-house','Allied',NULL,'f','pre_launch'),
  ('du-bois','Du Bois',NULL,'t','pre_launch'),
  ('gregory','Van Pelt / Gregory',NULL,'t','pre_launch'),
  ('gutmann','Gutmann',NULL,'t','pre_launch'),
  ('harnwell','Harnwell',NULL,'t','pre_launch'),
  ('harrison','Harrison',NULL,'t','pre_launch'),
  ('hill','Hill',NULL,'t','pre_launch'),
  ('kings-court','Kings Court English',NULL,'t','pre_launch'),
  ('lauder','Lauder',NULL,'t','pre_launch'),
  ('lower-quad','Lower Quad',NULL,'t','pre_launch'),
  ('mayer','Mayer',NULL,'t','pre_launch'),
  ('quad','Upper Quad',NULL,'t','pre_launch'),
  ('radian','Radian',NULL,'t','pre_launch'),
  ('rodin','Rodin',NULL,'t','pre_launch')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, desk_phone=EXCLUDED.desk_phone, is_staffable=EXCLUDED.is_staffable;

-- system_config. allow_time_travel is OMITTED on purpose: absent means time travel is
-- DENIED, which is what production must be (migration 20260726000008).
INSERT INTO system_config (config_key, config_value, value_type, notes) VALUES
  ('ack_deadline_offset_minutes','10','integer'::value_type_enum,NULL),
  ('drop_horizon_days','30','integer'::value_type_enum,NULL),
  ('float_retention_days','14','integer'::value_type_enum,NULL),
  ('float_swap_expiry_hours','24','integer'::value_type_enum,NULL),
  ('hm_working_hours_end','17:00','time_of_day'::value_type_enum,NULL),
  ('hm_working_hours_start','08:00','time_of_day'::value_type_enum,NULL),
  ('max_allied_coverage_blocks','8','integer'::value_type_enum,NULL),
  ('max_notification_delivery_attempts','12','integer'::value_type_enum,'Dispatch attempts before a notification is dead-lettered. With the capped exponential backoff below this is roughly 7 hours of retrying.'),
  ('min_float_chunk_blocks','1','integer'::value_type_enum,NULL),
  ('no_ack_trigger_offset_minutes','5','integer'::value_type_enum,NULL),
  ('notification_retry_backoff_cap_minutes','60','integer'::value_type_enum,'Ceiling on the exponential retry backoff between dispatch attempts.'),
  ('open_shift_permanent_horizon_weeks','26','integer'::value_type_enum,'How far ahead the PERMANENT-OPENINGS feed looks. Deliberately longer than the weekly horizon so a permanently-dropped slot stays pickable as a whole recurrence for the rest of the semester.'),
  ('open_shift_weekly_horizon_weeks','6','integer'::value_type_enum,'How far ahead the WEEKLY open-shifts feed looks. The mobile calendar navigates last-week…+4, so 6 weeks covers it with headroom. Bounds worker_open_shifts.'),
  ('operational_retention_days','28','integer'::value_type_enum,'Age past which delivered/terminal notifications and non-pending float assignments are deleted. Four weeks; after that the operational detail is not acted on. Deleting a float nulls shift_block_assignments.parent_float_id (ON DELETE SET NULL).'),
  ('permanent_swap_expiry_days','7','integer'::value_type_enum,NULL),
  ('project_administrator_user_id','a0000000-0000-4000-8000-00000000000b','uuid'::value_type_enum,NULL),
  ('retention_delete_batch_size','5000','integer'::value_type_enum,'Rows deleted per statement by the retention sweep. Chunked so the sweep never holds a long lock or emits one huge WAL record for Realtime to fan out.'),
  ('shift_block_minutes','30','integer'::value_type_enum,NULL),
  ('shift_swap_expiry_anchor','T-3h','enum'::value_type_enum,NULL)
ON CONFLICT (config_key) DO UPDATE SET config_value=EXCLUDED.config_value;

-- duty routing (issue type -> tier, with day/time/season windows)
INSERT INTO routing_rules (rule_id, issue_type, tier, day_type, window_start, window_end, season_scope, priority, active, notes) VALUES
  ('3b30ca68-7979-4992-89c4-24bea1f0c225','access','csmod','any',NULL,NULL,'any',10,'t','PLACEHOLDER: access issues to the student-manager (CSMOD) tier first'),
  ('9a2bfeaa-ca08-450c-b624-c576bc5fc3cb','equipment','rsm','any',NULL,NULL,'any',10,'t','PLACEHOLDER: equipment/IC issues to the RSM'),
  ('f3843f8c-6937-4169-9f5d-7a03742c9ccd','facilities','hmod','any',NULL,NULL,'any',20,'t','PLACEHOLDER: facilities to HMOD'),
  ('ead04580-f203-409f-b242-77b00838c0fe','general','hmod','any',NULL,NULL,'any',50,'t','PLACEHOLDER: default catch-all to HMOD')
ON CONFLICT (rule_id) DO NOTHING;

COMMIT;
