-- Tier 2: accounts, roles, memberships
-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.
--
-- Passwords carried verbatim (STAGING build).
--
-- FLAGGED, NOT HIDDEN: Hana Gregory (hm) and Diana Gregory (rsm) are NOT real people.
-- They are carried so Gregory has a coverage recipient. The 9 Gregory accounts use
-- firstname@upenn.edu placeholder addresses that MUST be replaced with deliverable Penn
-- addresses before the production load.
BEGIN;

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data,
  confirmation_token, recovery_token, email_change_token_new, email_change) VALUES
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000002','authenticated','authenticated','aaron@upenn.edu','$2a$06$1kfPbBwN2hiLSlAl9v8fieCRRRuPlIZE0jxQGuglMxCAoR.PC7Y/G', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Aaron"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','a0000000-0000-4000-8000-00000000000b','authenticated','authenticated','admin@upenn.edu','$2a$06$Py5ev6I.5lLsDKJzq.i5nOwrokkhPvyEtpd8JlikCUu0hAFdPmuEm', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000005','authenticated','authenticated','akkirui@sas.upenn.edu','$2a$06$XrY2iMbggLzRkFq//sUD4.fsPAXE4XysiWtp.3HFC8WEIdnoP.DPq', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Aaron"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','a111ed00-0000-4000-8000-000000000001','authenticated','authenticated','allied@upenn.edu','$2a$06$HXsanNVBXzmCsd/LjEoupumyJA5VLVQD7xKsg.G7UMWIpM1Qw0HrC', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Allied"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000010','authenticated','authenticated','amtaye@upenn.edu','$2a$06$zrJ2jPtGV8RnSs8oMjAK/.lzf4WkaDww4jT.JeKhib.JS6wtuuC1m', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Amaltuas Taye"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000008','authenticated','authenticated','amy@upenn.edu','$2a$06$vx6WniBU1JenLwxTW2M1PuMRdewZwL/ewJo2xrL6AumsCQkU01SMm', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Amy"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000001','authenticated','authenticated','awahan@upenn.edu','$2a$06$Ql5LTuJ/3xuJ.kl2KG7CKebUt.Cuv1vkGHGLS07t5bjExsOVMxbSa', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Awahan"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000008','authenticated','authenticated','chelimo@seas.upenn.edu','$2a$06$douHMdx0uIIkxM9/jOt0H.wMOQ.yP8520690CDuPg48GNQPc6/IqC', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Andrew Chelimo"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000003','authenticated','authenticated','dbukasa@sas.upenn.edu','$2a$06$hua49JUgRSAmiBIusTpVeuuDHiyTrVtQWBBXNSjpo09WhMT.k6kOy', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Drew"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','5ca50000-0000-4000-8000-000000000042','authenticated','authenticated','diana-gregory@upenn.edu','$2a$06$2Uu8kc./mRvBywZ7pmL2Te/eJxyPGqCo40lTs/Nfs5jjau5it0HTa', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000001','authenticated','authenticated','elenikan@sas.upenn.edu','$2a$06$5Ke/hhvSwQrEn1t5BpRCCuFpE3ZMhM5SKtKlRPkarAOQtlPteS86C', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Eleni"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000004','authenticated','authenticated','eleni@upenn.edu','$2a$06$X8yEg0kW8aqGOT.lQMurqu2/7ls/DXvVs.TwkLHYBPj2w26XFUa.a', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Eleni"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','5ca50000-0000-4000-8000-000000000041','authenticated','authenticated','hana-gregory@upenn.edu','$2a$06$fZtAfsVYn32/aaA8f4nsHeV.xs6zBnQY4DiU.e6u/1Wc7HybgNsQu', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000005','authenticated','authenticated','khalil@upenn.edu','$2a$06$Eio0HnnVbfVWToNS4X1BgeBPgaHuP6BTeFYDXzrz8XP9eK5mcPfX6', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Khalil"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000009','authenticated','authenticated','liseche1@nursing.upenn.edu','$2a$06$1/TJYaCmFCklTYk86iL5B.UIzXcJ87GweLJ/VlIfiHNxYgZsFxASi', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Purity"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000006','authenticated','authenticated','lmelesse@seas.upenn.edu','$2a$06$MprSYHWIE3uGf3o4s9NE5ewMeF76i.jyVva44pAXkT8p1AyJB2Ome', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Lealem"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000004','authenticated','authenticated','mercadov@sas.upenn.edu','$2a$06$ea04ygOIHwa54LdnkaRFr.TISdb9DqrQopmK1L1Fl2ZVQ0PQsWa9m', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Valeria"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','a012a6b8-4f8d-4837-976c-7b0fbc60f8f9','authenticated','authenticated','mmajeski@upenn.edu','$2a$06$jKlZqeEGWDR9Zi6FLaNmqOZ67q2xAhwJtorwU4n2Uc8j6DgKvUkWm', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Mitchelle Majeski"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000002','authenticated','authenticated','ndlovuab@sas.upenn.edu','$2a$06$oOQX5cFsBkwaiKJSUy1Z9.Wtlpk9E9UJj5etGUN4qwBoO37fH.6rW', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Abraham"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000009','authenticated','authenticated','novia@upenn.edu','$2a$06$FDMnVEoJ1B/EZjRbyOtzVO64yIugPaqYXqPdc1ogxvfpLiPStZUoq', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Novia"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','fbb00000-0000-4000-8000-000000000007','authenticated','authenticated','ornellar@sas.upenn.edu','$2a$06$y1NVjkTIwP7KeVguPFm0JOKmP/V4f0JpzClSrvfW2ZMZRZKcos0ka', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Ornella"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000007','authenticated','authenticated','richard@upenn.edu','$2a$06$9x04v9AY8A1ITmSXu5h5hOPl/HqIriD3TGSNgCcPo.LX0GwIBnNhm', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Richard"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000006','authenticated','authenticated','victor@upenn.edu','$2a$06$OVbWVFwApQ9dP1OqLCT2a.bho.TGYZASQTaPkY32iTRIsfLWgTNr6', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Victor"}'::jsonb, '','','',''),
  ('00000000-0000-0000-0000-000000000000','9ce70000-0000-4000-8000-000000000003','authenticated','authenticated','zara@upenn.edu','$2a$06$QNIfIXOnJUe3oXpYAklOA.vgYDYND/W7aM4TxvmJTh/QwoDjFVYqu', now(),now(),now(), '{"provider": "email", "providers": ["email"]}'::jsonb, '{"name": "Zara"}'::jsonb, '','','','')
ON CONFLICT (id) DO NOTHING;

INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at) VALUES
  ('9ce70000-0000-4000-8000-000000000002','9ce70000-0000-4000-8000-000000000002','{"sub" : "9ce70000-0000-4000-8000-000000000002", "email" : "aaron@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('a0000000-0000-4000-8000-00000000000b','a0000000-0000-4000-8000-00000000000b','{"sub" : "a0000000-0000-4000-8000-00000000000b", "email" : "admin@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000005','fbb00000-0000-4000-8000-000000000005','{"sub" : "fbb00000-0000-4000-8000-000000000005", "email" : "akkirui@sas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('a111ed00-0000-4000-8000-000000000001','a111ed00-0000-4000-8000-000000000001','{"sub" : "a111ed00-0000-4000-8000-000000000001", "email" : "allied@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000010','fbb00000-0000-4000-8000-000000000010','{"sub" : "fbb00000-0000-4000-8000-000000000010", "email" : "amtaye@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000008','9ce70000-0000-4000-8000-000000000008','{"sub" : "9ce70000-0000-4000-8000-000000000008", "email" : "amy@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000001','9ce70000-0000-4000-8000-000000000001','{"sub" : "9ce70000-0000-4000-8000-000000000001", "email" : "awahan@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000008','fbb00000-0000-4000-8000-000000000008','{"sub" : "fbb00000-0000-4000-8000-000000000008", "email" : "chelimo@seas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000003','fbb00000-0000-4000-8000-000000000003','{"sub" : "fbb00000-0000-4000-8000-000000000003", "email" : "dbukasa@sas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('5ca50000-0000-4000-8000-000000000042','5ca50000-0000-4000-8000-000000000042','{"sub" : "5ca50000-0000-4000-8000-000000000042", "email" : "diana-gregory@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000001','fbb00000-0000-4000-8000-000000000001','{"sub" : "fbb00000-0000-4000-8000-000000000001", "email" : "elenikan@sas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000004','9ce70000-0000-4000-8000-000000000004','{"sub" : "9ce70000-0000-4000-8000-000000000004", "email" : "eleni@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('5ca50000-0000-4000-8000-000000000041','5ca50000-0000-4000-8000-000000000041','{"sub" : "5ca50000-0000-4000-8000-000000000041", "email" : "hana-gregory@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000005','9ce70000-0000-4000-8000-000000000005','{"sub" : "9ce70000-0000-4000-8000-000000000005", "email" : "khalil@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000009','fbb00000-0000-4000-8000-000000000009','{"sub" : "fbb00000-0000-4000-8000-000000000009", "email" : "liseche1@nursing.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000006','fbb00000-0000-4000-8000-000000000006','{"sub" : "fbb00000-0000-4000-8000-000000000006", "email" : "lmelesse@seas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000004','fbb00000-0000-4000-8000-000000000004','{"sub" : "fbb00000-0000-4000-8000-000000000004", "email" : "mercadov@sas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('a012a6b8-4f8d-4837-976c-7b0fbc60f8f9','a012a6b8-4f8d-4837-976c-7b0fbc60f8f9','{"sub" : "a012a6b8-4f8d-4837-976c-7b0fbc60f8f9", "email" : "mmajeski@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000002','fbb00000-0000-4000-8000-000000000002','{"sub" : "fbb00000-0000-4000-8000-000000000002", "email" : "ndlovuab@sas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000009','9ce70000-0000-4000-8000-000000000009','{"sub" : "9ce70000-0000-4000-8000-000000000009", "email" : "novia@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('fbb00000-0000-4000-8000-000000000007','fbb00000-0000-4000-8000-000000000007','{"sub" : "fbb00000-0000-4000-8000-000000000007", "email" : "ornellar@sas.upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000007','9ce70000-0000-4000-8000-000000000007','{"sub" : "9ce70000-0000-4000-8000-000000000007", "email" : "richard@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000006','9ce70000-0000-4000-8000-000000000006','{"sub" : "9ce70000-0000-4000-8000-000000000006", "email" : "victor@upenn.edu"}'::jsonb,'email', now(),now(),now()),
  ('9ce70000-0000-4000-8000-000000000003','9ce70000-0000-4000-8000-000000000003','{"sub" : "9ce70000-0000-4000-8000-000000000003", "email" : "zara@upenn.edu"}'::jsonb,'email', now(),now(),now())
ON CONFLICT (provider, provider_id) DO NOTHING;

INSERT INTO users (user_id, name, email, home_house_id, is_active, broadcast_subscribed) VALUES
  ('9ce70000-0000-4000-8000-000000000002','Aaron','aaron@upenn.edu','gregory','t','f'),
  ('a0000000-0000-4000-8000-00000000000b','Project Administrator','admin@upenn.edu','quad','t','f'),
  ('fbb00000-0000-4000-8000-000000000005','Aaron','akkirui@sas.upenn.edu','harnwell','t','f'),
  ('a111ed00-0000-4000-8000-000000000001','Allied','allied@upenn.edu','allied-house','t','f'),
  ('fbb00000-0000-4000-8000-000000000010','Amaltuas Taye','amtaye@upenn.edu','harnwell','t','f'),
  ('9ce70000-0000-4000-8000-000000000008','Amy','amy@upenn.edu','gregory','t','f'),
  ('9ce70000-0000-4000-8000-000000000001','Awahan','awahan@upenn.edu','gregory','t','f'),
  ('fbb00000-0000-4000-8000-000000000008','Andrew Chelimo','chelimo@seas.upenn.edu','harnwell','t','f'),
  ('fbb00000-0000-4000-8000-000000000003','Drew','dbukasa@sas.upenn.edu','harnwell','t','f'),
  ('5ca50000-0000-4000-8000-000000000042','Diana Gregory','diana-gregory@upenn.edu','gregory','t','f'),
  ('fbb00000-0000-4000-8000-000000000001','Eleni','elenikan@sas.upenn.edu','harnwell','t','f'),
  ('9ce70000-0000-4000-8000-000000000004','Eleni','eleni@upenn.edu','gregory','t','f'),
  ('5ca50000-0000-4000-8000-000000000041','Hana Gregory','hana-gregory@upenn.edu','gregory','t','f'),
  ('9ce70000-0000-4000-8000-000000000005','Khalil','khalil@upenn.edu','gregory','t','f'),
  ('fbb00000-0000-4000-8000-000000000009','Purity','liseche1@nursing.upenn.edu','harnwell','t','f'),
  ('fbb00000-0000-4000-8000-000000000006','Lealem','lmelesse@seas.upenn.edu','harnwell','t','f'),
  ('fbb00000-0000-4000-8000-000000000004','Valeria','mercadov@sas.upenn.edu','harnwell','t','f'),
  ('a012a6b8-4f8d-4837-976c-7b0fbc60f8f9','Mitchelle Majeski','mmajeski@upenn.edu','harnwell','t','f'),
  ('fbb00000-0000-4000-8000-000000000002','Abraham','ndlovuab@sas.upenn.edu','harnwell','t','f'),
  ('9ce70000-0000-4000-8000-000000000009','Novia','novia@upenn.edu','gregory','t','f'),
  ('fbb00000-0000-4000-8000-000000000007','Ornella','ornellar@sas.upenn.edu','harnwell','t','f'),
  ('9ce70000-0000-4000-8000-000000000007','Richard','richard@upenn.edu','gregory','t','f'),
  ('9ce70000-0000-4000-8000-000000000006','Victor','victor@upenn.edu','gregory','t','f'),
  ('9ce70000-0000-4000-8000-000000000003','Zara','zara@upenn.edu','gregory','t','f')
ON CONFLICT (user_id) DO UPDATE SET name=EXCLUDED.name, email=EXCLUDED.email, home_house_id=EXCLUDED.home_house_id, is_active=EXCLUDED.is_active;

INSERT INTO user_roles (user_id, role, scope_house_id) VALUES
  ('5ca50000-0000-4000-8000-000000000041','hm'::user_role_enum,'gregory'),
  ('5ca50000-0000-4000-8000-000000000042','rsm'::user_role_enum,'gregory'),
  ('9ce70000-0000-4000-8000-000000000001','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000002','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000003','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000004','sm'::user_role_enum,'gregory'),
  ('9ce70000-0000-4000-8000-000000000005','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000006','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000007','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000008','sw'::user_role_enum,NULL),
  ('9ce70000-0000-4000-8000-000000000009','sw'::user_role_enum,NULL),
  ('a0000000-0000-4000-8000-00000000000b','admin'::user_role_enum,NULL),
  ('a012a6b8-4f8d-4837-976c-7b0fbc60f8f9','hm'::user_role_enum,'harnwell'),
  ('a111ed00-0000-4000-8000-000000000001','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000001','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000002','sm'::user_role_enum,'harnwell'),
  ('fbb00000-0000-4000-8000-000000000002','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000003','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000004','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000005','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000006','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000007','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000008','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000009','sw'::user_role_enum,NULL),
  ('fbb00000-0000-4000-8000-000000000010','rsm'::user_role_enum,'harnwell')
ON CONFLICT DO NOTHING;

-- season-scoped membership; users.home_house_id is the cache of the row covering today
INSERT INTO user_house_memberships (membership_id, user_id, house_id, effective_from, effective_to, applied_at, note) VALUES
  ('a893f69a-f3d0-4f34-9700-853bef6ddc7a','5ca50000-0000-4000-8000-000000000041','gregory','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('0b4b5918-9b78-414b-974c-fc52c220f9f7','5ca50000-0000-4000-8000-000000000042','gregory','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('17d575de-2825-49ac-8fce-c59a3a5501ac','9ce70000-0000-4000-8000-000000000001','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('cb289117-8b50-441f-b722-ba91d18c9726','9ce70000-0000-4000-8000-000000000002','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('fd9b65cb-7865-45d6-ac5c-5b377ef0c81a','9ce70000-0000-4000-8000-000000000003','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('e6c9c07a-b4ee-409c-aeb0-3bd273540e38','9ce70000-0000-4000-8000-000000000004','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('6efc25bc-3a8c-400c-b933-672cdff956b5','9ce70000-0000-4000-8000-000000000005','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('7469154a-4bb5-4e29-9202-076a6ff93da8','9ce70000-0000-4000-8000-000000000006','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('35558b0e-a3d4-4dc1-90f6-39333dcbbf97','9ce70000-0000-4000-8000-000000000007','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('bc556e65-8675-4dc6-a36c-7e14729234de','9ce70000-0000-4000-8000-000000000008','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('67b8c222-5998-404c-9b5b-f34f4c73e328','9ce70000-0000-4000-8000-000000000009','gregory','2000-01-01',NULL,'2026-07-26 01:05:37.166875+00',NULL),
  ('6cd559a6-814d-4d36-98d5-0975cb8f6c4a','a0000000-0000-4000-8000-00000000000b','quad','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('cef2b201-7b74-4292-8241-2e52d56a3c6a','a012a6b8-4f8d-4837-976c-7b0fbc60f8f9','harnwell','2026-07-26',NULL,'2026-07-26 01:11:38.518122+00',NULL),
  ('c0043871-3dbe-46ba-a44e-aa9bfc3819fd','a111ed00-0000-4000-8000-000000000001','allied-house','2000-01-01',NULL,'2026-07-26 01:33:33.032304+00',NULL),
  ('392184b5-7096-45a5-a761-e6a3e4c0a1cc','fbb00000-0000-4000-8000-000000000001','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('6c3d8c81-000d-44e8-9ca6-1e5b753213ee','fbb00000-0000-4000-8000-000000000002','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('a74249ce-0519-4906-b125-af9ae4892b0e','fbb00000-0000-4000-8000-000000000003','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('8aec1273-362d-48e5-941f-08205415bc1d','fbb00000-0000-4000-8000-000000000004','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('aff03502-b7bc-41d7-a782-dc82079c4f5e','fbb00000-0000-4000-8000-000000000005','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('87443ceb-87dc-445e-8ec5-bfa072115612','fbb00000-0000-4000-8000-000000000006','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('4e3dc531-a4a8-4b73-8c32-23d3c1b9f1ee','fbb00000-0000-4000-8000-000000000007','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('2fa2a496-bb52-42e2-975b-7225d0c54f3c','fbb00000-0000-4000-8000-000000000008','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('b59a6d8b-6934-4411-bd72-5b45a2c4d696','fbb00000-0000-4000-8000-000000000009','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL),
  ('339fc30b-56eb-40cf-85b6-52907a05e1f8','fbb00000-0000-4000-8000-000000000010','harnwell','2000-01-01',NULL,'2026-07-21 20:40:20.751037+00',NULL)
ON CONFLICT (membership_id) DO NOTHING;

-- the urgent-notification terminal contact must resolve to an active user
UPDATE system_config SET config_value='a0000000-0000-4000-8000-00000000000b' WHERE config_key='project_administrator_user_id';

COMMIT;
