-- Tier 3: AUTHORED season configuration only
-- AUTO-GENERATED by scripts/gen-prod-seed.sh. Do not hand-edit.
--
-- Writes authoring tables ONLY. operating_profiles, staffing_patterns,
-- operating_calendar, float_routing and shift_blocks are DERIVED and are produced by
-- apply_compiled_season, which the runbook runs (dry-run first) after this loads.
BEGIN;

INSERT INTO operating_seasons (season_id, season_name, slug, start_date, end_date, scheduling_mode, hours_cap, cap_enforcement, shift_start_bound, shift_end_bound, created_by, created_at, preference_deadline) VALUES
  ('5ea50000-0000-4000-8000-000000000001','Summer 2026','summer2026','2026-06-01','2026-08-20','sm_built'::scheduling_mode_enum,40,'hard'::cap_enforcement_enum,'05:30:00','00:00:00','a0000000-0000-4000-8000-00000000000b', now(),'2026-05-29 03:59:00+00')
ON CONFLICT (season_id) DO NOTHING;

-- per-house day-type bands; an empty band list means closed that day type
INSERT INTO season_house_windows (window_id, season_id, house_id, start_date, end_date, weekday_bands, weekend_bands) VALUES
  ('7d3fc061-b33c-4073-b94e-d5df772876c5','5ea50000-0000-4000-8000-000000000001','du-bois','2026-06-01','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('46a41070-e4ba-4fc2-bf77-fc127a921c96','5ea50000-0000-4000-8000-000000000001','gregory','2026-06-01','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "08:00"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "08:00"}]'::jsonb),
  ('4abe3d4d-9b69-4ea3-8b7a-b637a7d894ec','5ea50000-0000-4000-8000-000000000001','gutmann','2026-06-01','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('aebe4b0e-9d0a-4820-a61c-1863f5c21f01','5ea50000-0000-4000-8000-000000000001','harnwell','2026-06-01','2026-08-20','[{"block_end": "12:00", "headcount": 1, "block_start": "05:30"}, {"block_end": "00:00", "headcount": 2, "block_start": "12:00"}]'::jsonb,'[{"block_end": "00:00", "headcount": 2, "block_start": "05:30"}]'::jsonb),
  ('af779259-0ffa-4dc1-86cd-8925c14723f0','5ea50000-0000-4000-8000-000000000001','harrison','2026-06-25','2026-08-20','[{"block_end": "12:00", "headcount": 1, "block_start": "05:30"}, {"block_end": "00:00", "headcount": 2, "block_start": "12:00"}]'::jsonb,'[{"block_end": "00:00", "headcount": 2, "block_start": "05:30"}]'::jsonb),
  ('2ba00b91-b8b0-423e-b5a2-ceb71104e9bb','5ea50000-0000-4000-8000-000000000001','harrison','2026-06-08','2026-06-24','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('1bd1900a-cd35-4422-ad9b-14a439fa972e','5ea50000-0000-4000-8000-000000000001','hill','2026-06-01','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('ff652a47-0016-4391-98cb-50ff51306f87','5ea50000-0000-4000-8000-000000000001','kings-court','2026-06-01','2026-06-13','[{"block_end": "17:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[]'::jsonb),
  ('ff5ac1b0-8922-4e86-bbea-d2cfa57e06b2','5ea50000-0000-4000-8000-000000000001','kings-court','2026-06-14','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('36587e74-eee4-44a6-a4fa-5a59e2077df6','5ea50000-0000-4000-8000-000000000001','lauder','2026-06-01','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('70b4a549-dfed-48a9-b337-16741cc97201','5ea50000-0000-4000-8000-000000000001','mayer','2026-06-01','2026-08-20','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb),
  ('9950070e-75d7-47d8-bf28-0a06ee58e517','5ea50000-0000-4000-8000-000000000001','rodin','2026-06-17','2026-08-20','[{"block_end": "12:00", "headcount": 1, "block_start": "05:30"}, {"block_end": "00:00", "headcount": 2, "block_start": "12:00"}]'::jsonb,'[{"block_end": "00:00", "headcount": 2, "block_start": "05:30"}]'::jsonb),
  ('b069a762-8221-4546-9a8b-d50361d90244','5ea50000-0000-4000-8000-000000000001','rodin','2026-06-01','2026-06-16','[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb,'[{"block_end": "00:00", "headcount": 1, "block_start": "05:30"}]'::jsonb)
ON CONFLICT (window_id) DO NOTHING;

INSERT INTO season_float_windows (window_id, season_id, start_date, end_date) VALUES
  ('7d3378a2-57b9-451d-8710-709de73ee7e5','5ea50000-0000-4000-8000-000000000001','2026-07-01','2026-08-20')
ON CONFLICT (window_id) DO NOTHING;

-- the scheduling period the builder and preferences hang off
INSERT INTO scheduling_periods (period_id, period_name, profile_name, start_date, end_date, preference_deadline) VALUES
  ('5ea50000-0000-4000-8000-000000000001','Summer 2026','s_summer2026_20260601','2026-06-01','2026-08-20','2026-05-29 03:59:00+00')
ON CONFLICT (period_id) DO NOTHING;

COMMIT;
