// Generated by scripts/brand/build-icons.mjs from scripts/brand/geometry.mjs. Do not edit by hand.
// The chevronel, on the shared 100x100 artboard. See docs/design/logo.md.

import CoreGraphics

enum BrandMarkGeometry {
    static let artboard: CGFloat = 100

    /// Upper (Penn red) chevron outline.
    static let upper: [CGPoint] = [
        CGPoint(x: 16.3523, y: 51.5803),
        CGPoint(x: 50.0000, y: 15.6894),
        CGPoint(x: 83.6477, y: 51.5803),
        CGPoint(x: 76.3523, y: 58.4197),
        CGPoint(x: 50.0000, y: 30.3106),
        CGPoint(x: 23.6477, y: 58.4197),
    ]

    /// Lower (Penn navy) chevron outline.
    static let lower: [CGPoint] = [
        CGPoint(x: 14.8932, y: 75.2124),
        CGPoint(x: 50.0000, y: 37.7652),
        CGPoint(x: 85.1068, y: 75.2124),
        CGPoint(x: 74.8932, y: 84.7876),
        CGPoint(x: 50.0000, y: 58.2348),
        CGPoint(x: 25.1068, y: 84.7876),
    ]

    /// Plate centres, on the lower chevron's centreline.
    static let plates: [CGPoint] = [
        CGPoint(x: 50.0000, y: 48.0000),
        CGPoint(x: 36.3212, y: 62.5907),
        CGPoint(x: 63.6788, y: 62.5907),
    ]

    static let plateRadius: CGFloat = 5.2

    /// Tight bounds of the whole mark, for centring inside a tile.
    static let markBounds = CGRect(
        x: 14.8932, y: 15.6894,
        width: 70.2135, height: 69.0982)
}
